<?php

namespace ComakeitBundle\Repository;

/**
 * SymptomsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SymptomsRepository extends \Doctrine\ORM\EntityRepository
{
}
