<?php

namespace ComakeitBundle\Repository;

/**
 * SymtomsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SymtomsRepository extends \Doctrine\ORM\EntityRepository
{
}
